# Generated by Django 2.2.1 on 2019-05-19 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolists', '0002_auto_20190518_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deadline',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='todo',
            name='importance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todo',
            name='isFinished',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='TITLE'),
        ),
    ]
