# Generated by Django 2.2.1 on 2019-05-19 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolists', '0003_auto_20190520_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='todo',
            name='importance',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='todo',
            name='isFinished',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
