# Generated by Django 2.2.1 on 2019-05-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolists', '0004_auto_20190520_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(blank=True),
        ),
    ]
