# Generated by Django 2.2.1 on 2019-05-19 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolists', '0006_auto_20190520_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='starttime',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
