# Generated by Django 2.2.1 on 2019-05-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolists', '0008_auto_20190520_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='starttime',
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
